product_ids:
- 00-USD
- 1INCH-BTC
- 1INCH-EUR
- 1INCH-GBP
- 1INCH-USD
- 2Z-USD
- A8-USD
- AAVE-BTC
- AAVE-EUR
- AAVE-GBP
- AAVE-USD
- ABT-USD
- ACH-USD
- ACH-USDT
- ACS-USD
- ACX-USD
- ADA-BTC
- ADA-ETH
- ADA-EUR
- ADA-GBP
- ADA-USD
- ADA-USDC
- ADA-USDT
- AERGO-USD
- AERO-USD
- AGLD-USD
- AGLD-USDT
- AIOZ-USD
- AIOZ-USDT
- AKT-USD
- ALCX-EUR
- ALCX-USD
- ALCX-USDT
- ALEO-USD
- ALEPH-USD
- ALGO-BTC
- ALGO-EUR
- ALGO-GBP
- ALGO-USD
- ALICE-USD
- ALLO-USD
- ALT-USD
- AMP-USD
- ANKR-BTC
- ANKR-EUR
- ANKR-GBP
- ANKR-USD
- ANT-USD
- APE-EUR
- APE-USD
- APE-USDT
- API3-USD
- API3-USDT
- APR-USD
- APT-USD
- APT-USDT
- ARB-USD
- ARKM-USD
- ARPA-EUR
- ARPA-USD
- ARPA-USDT
- ASM-USD
- ASM-USDT
- AST-USD
- ASTER-USD
- ATA-USD
- ATA-USDT
- ATH-USD
- ATOM-BTC
- ATOM-EUR
- ATOM-GBP
- ATOM-USD
- ATOM-USDT
- AUCTION-EUR
- AUCTION-USD
- AUCTION-USDT
- AUDD-USDC
- AUDIO-USD
- AURORA-USD
- AVAX-BTC
- AVAX-EUR
- AVAX-USD
- AVAX-USDT
- AVNT-USD
- AVT-USD
- AWE-USD
- AXL-USD
- AXS-BTC
- AXS-EUR
- AXS-USD
- AXS-USDT
- B3-USD
- BADGER-EUR
- BADGER-USD
- BADGER-USDT
- BAL-BTC
- BAL-USD
- BAND-BTC
- BAND-EUR
- BAND-GBP
- BAND-USD
- BARD-USD
- BAT-BTC
- BAT-ETH
- BAT-EUR
- BAT-USD
- BAT-USDC
- BCH-BTC
- BCH-EUR
- BCH-GBP
- BCH-USD
- BEAM-USD
- BERA-USD
- BICO-EUR
- BICO-USD
- BICO-USDT
- BIGTIME-USD
- BIO-USD
- BIT-USD
- BIT-USDT
- BLAST-USD
- BLUR-USD
- BLZ-USD
- BNB-USD
- BNKR-USD
- BNT-BTC
- BNT-EUR
- BNT-GBP
- BNT-USD
- BOBA-USD
- BOBA-USDT
- BOBBOB-USD
- BOND-USD
- BOND-USDT
- BONK-USD
- BREV-USD
- BTC-EUR
- BTC-GBP
- BTC-USD
- BTC-USDC
- BTC-USDT
- BTRST-BTC
- BTRST-EUR
- BTRST-GBP
- BTRST-USD
- BTRST-USDT
- BUSD-USD
- C98-USD
- C98-USDT
- CAKE-USD
- CBETH-ETH
- CBETH-USD
- CELR-USD
- CFG-USD
- CGLD-BTC
- CGLD-EUR
- CGLD-GBP
- CGLD-USD
- CHZ-EUR
- CHZ-GBP
- CHZ-USD
- CHZ-USDT
- CLANKER-USD
- CLV-EUR
- CLV-GBP
- CLV-USD
- CLV-USDT
- COMP-BTC
- COMP-USD
- COOKIE-USD
- CORECHAIN-USD
- COSMOSDYDX-USD
- COTI-USD
- COVAL-USD
- COVAL-USDT
- COW-USD
- CRO-EUR
- CRO-USD
- CRO-USDT
- CRPT-USD
- CRV-BTC
- CRV-EUR
- CRV-GBP
- CRV-USD
- CTSI-BTC
- CTSI-USD
- CTX-EUR
- CTX-USD
- CTX-USDT
- CVC-USD
- CVC-USDC
- CVX-USD
- DAI-USD
- DAI-USDC
- DAR-USD
- DASH-BTC
- DASH-USD
- DBR-USD
- DDX-EUR
- DDX-USD
- DDX-USDT
- DEGEN-USD
- DESO-EUR
- DESO-USD
- DESO-USDT
- DEXT-USD
- DIA-EUR
- DIA-USD
- DIA-USDT
- DIMO-USD
- DNT-USD
- DNT-USDC
- DOGE-BTC
- DOGE-EUR
- DOGE-GBP
- DOGE-USD
- DOGE-USDT
- DOGINME-USD
- DOLO-USD
- DOT-BTC
- DOT-EUR
- DOT-GBP
- DOT-USD
- DOT-USDT
- DREP-USD
- DREP-USDT
- DRIFT-USD
- DYP-USD
- DYP-USDT
- EDGE-USD
- EGLD-USD
- EIGEN-USD
- ELA-USD
- ELA-USDT
- ELSA-USD
- ENA-USD
- ENJ-BTC
- ENJ-USD
- ENJ-USDT
- ENS-EUR
- ENS-USD
- ENS-USDT
- EOS-BTC
- EOS-EUR
- EOS-USD
- ERA-USD
- ERN-EUR
- ERN-USD
- ERN-USDT
- ETC-BTC
- ETC-EUR
- ETC-GBP
- ETC-USD
- ETH-BTC
- ETH-DAI
- ETH-EUR
- ETH-GBP
- ETH-USD
- ETH-USDC
- ETH-USDT
- ETHFI-USD
- EUL-USD
- EURC-EUR
- EURC-USD
- EURC-USDC
- FAI-USD
- FARM-USD
- FARM-USDT
- FARTCOIN-USD
- FET-USD
- FET-USDT
- FIDA-EUR
- FIDA-USD
- FIDA-USDT
- FIGHT-USD
- FIL-BTC
- FIL-EUR
- FIL-GBP
- FIL-USD
- FIS-USD
- FIS-USDT
- FLOCK-USD
- FLOKI-USD
- FLOW-USD
- FLOW-USDT
- FLR-USD
- FLUID-USD
- FORT-USD
- FORT-USDT
- FORTH-BTC
- FORTH-EUR
- FORTH-GBP
- FORTH-USD
- FOX-USD
- FOX-USDT
- FUN1-USD
- FX-USD
- G-USD
- GAL-USD
- GAL-USDT
- GALA-EUR
- GALA-USD
- GALA-USDT
- GFI-USD
- GHST-USD
- GIGA-USD
- GLM-USD
- GMT-USD
- GMT-USDT
- GNO-USD
- GNO-USDT
- GNT-USDC
- GODS-USD
- GRT-BTC
- GRT-EUR
- GRT-GBP
- GRT-USD
- GST-USD
- GTC-USD
- GUSD-USD
- GYEN-USD
- HBAR-USD
- HBAR-USDT
- HFT-USD
- HFT-USDT
- HIGH-USD
- HNT-USD
- HOME-USD
- HONEY-USD
- HOPR-USD
- HOPR-USDT
- HYPER-USD
- ICP-BTC
- ICP-EUR
- ICP-GBP
- ICP-USD
- ICP-USDT
- IDEX-USD
- IDEX-USDT
- ILV-USD
- IMU-USD
- IMX-USD
- IMX-USDT
- INDEX-USD
- INDEX-USDT
- INJ-USD
- INV-USD
- IO-USD
- IOTX-EUR
- IOTX-USD
- IP-USD
- IRYS-USD
- JASMY-USD
- JASMY-USDT
- JITOSOL-USD
- JTO-USD
- JUP-USD
- JUPITER-USD
- KAITO-USD
- KARRAT-USD
- KAVA-USD
- KEEP-USD
- KERNEL-USD
- KEYCAT-USD
- KITE-USD
- KMNO-USD
- KNC-BTC
- KNC-USD
- KRL-EUR
- KRL-USD
- KRL-USDT
- KSM-USD
- KSM-USDT
- KTA-USD
- L3-USD
- LA-USD
- LAYER-USD
- LCX-EUR
- LCX-USD
- LCX-USDT
- LDO-USD
- LIGHTER-USD
- LINEA-USD
- LINK-BTC
- LINK-ETH
- LINK-EUR
- LINK-GBP
- LINK-USD
- LINK-USDT
- LIT-USD
- LOKA-USD
- LOOM-USD
- LOOM-USDC
- LPT-USD
- LQTY-EUR
- LQTY-USD
- LQTY-USDT
- LRC-BTC
- LRC-USD
- LRC-USDT
- LRDS-USD
- LSETH-ETH
- LSETH-USD
- LTC-BTC
- LTC-EUR
- LTC-GBP
- LTC-USD
- MAGIC-USD
- MAMO-USD
- MANA-BTC
- MANA-ETH
- MANA-EUR
- MANA-USD
- MANA-USDC
- MANTLE-USD
- MASK-EUR
- MASK-GBP
- MASK-USD
- MASK-USDT
- MATH-USD
- MATH-USDT
- MATIC-BTC
- MATIC-EUR
- MATIC-GBP
- MATIC-USD
- MATIC-USDT
- MCO2-USD
- MCO2-USDT
- MDT-USD
- MDT-USDT
- ME-USD
- MEDIA-USD
- MEDIA-USDT
- MET-USD
- METIS-USD
- METIS-USDT
- MINA-EUR
- MINA-USD
- MINA-USDT
- MIR-BTC
- MIR-EUR
- MIR-GBP
- MIR-USD
- MKR-BTC
- MKR-USD
- MLN-USD
- MNDE-USD
- MOBILE-USD
- MOG-USD
- MON-USD
- MONA-USD
- MOODENG-USD
- MORPHO-USD
- MOVE-USD
- MPL-USD
- MPLX-USD
- MSOL-USD
- MTL-USD
- MULTI-USD
- MUSD-USD
- MUSE-USD
- MXC-USD
- NCT-EUR
- NCT-USD
- NCT-USDT
- NEAR-USD
- NEAR-USDT
- NEON-USD
- NEST-USD
- NEST-USDT
- NEWT-USD
- NKN-BTC
- NKN-EUR
- NKN-GBP
- NKN-USD
- NMR-BTC
- NMR-EUR
- NMR-GBP
- NMR-USD
- NOICE-USD
- NOM-USD
- NU-BTC
- NU-EUR
- NU-GBP
- NU-USD
- OCEAN-USD
- OGN-BTC
- OGN-USD
- OMG-BTC
- OMG-EUR
- OMG-GBP
- OMG-USD
- OMNI-USD
- ONDO-USD
- OOKI-USD
- OP-USD
- OP-USDT
- ORCA-USD
- ORN-BTC
- ORN-USD
- ORN-USDT
- OSMO-USD
- OXT-USD
- PAX-USD
- PAX-USDT
- PAXG-USD
- PENDLE-USD
- PENGU-USD
- PEPE-USD
- PERP-EUR
- PERP-USD
- PERP-USDT
- PIRATE-USD
- PLA-USD
- PLU-USD
- PLUME-USD
- PNG-USD
- PNUT-USD
- POL-USD
- POLS-USD
- POLS-USDT
- POLY-USD
- POLY-USDT
- POND-USD
- POND-USDT
- POPCAT-USD
- POWR-EUR
- POWR-USD
- POWR-USDT
- PRCL-USD
- PRIME-USD
- PRO-USD
- PROMPT-USD
- PROVE-USD
- PRQ-USD
- PRQ-USDT
- PUMP-USD
- PUNDIX-USD
- PYR-USD
- PYTH-USD
- PYUSD-USD
- QI-USD
- QNT-USD
- QNT-USDT
- QSP-USD
- QSP-USDT
- QUICK-USD
- RAD-BTC
- RAD-EUR
- RAD-GBP
- RAD-USD
- RAD-USDT
- RAI-USD
- RARE-USD
- RARI-USD
- RAY-USD
- RBN-USD
- RECALL-USD
- RED-USD
- REN-BTC
- REN-USD
- RENDER-USD
- REP-BTC
- REP-USD
- REQ-BTC
- REQ-EUR
- REQ-GBP
- REQ-USD
- REQ-USDT
- REZ-USD
- RGT-USD
- RLC-BTC
- RLC-USD
- RLS-USD
- RLY-EUR
- RLY-GBP
- RLY-USD
- RLY-USDT
- RNDR-EUR
- RNDR-USD
- RNDR-USDT
- RONIN-USD
- ROSE-USD
- ROSE-USDT
- RPL-USD
- RSC-USD
- RSR-USD
- S-USD
- SAFE-USD
- SAND-USD
- SAND-USDT
- SAPIEN-USD
- SD-USD
- SEAM-USD
- SEI-USD
- SENT-USD
- SHDW-USD
- SHIB-EUR
- SHIB-GBP
- SHIB-USD
- SHIB-USDT
- SHPING-EUR
- SHPING-USD
- SHPING-USDT
- SKL-BTC
- SKL-EUR
- SKL-GBP
- SKL-USD
- SKR-USD
- SKY-USD
- SNT-USD
- SNX-BTC
- SNX-EUR
- SNX-GBP
- SNX-USD
- SOL-BTC
- SOL-ETH
- SOL-EUR
- SOL-GBP
- SOL-USD
- SOL-USDT
- SPA-USD
- SPELL-USD
- SPELL-USDT
- SPK-USD
- SPX-USD
- SQD-USD
- STG-USD
- STG-USDT
- STORJ-BTC
- STORJ-USD
- STRK-USD
- STX-USD
- STX-USDT
- SUI-USD
- SUKU-EUR
- SUKU-USD
- SUKU-USDT
- SUP-USD
- SUPER-USD
- SUPER-USDT
- SUSHI-BTC
- SUSHI-ETH
- SUSHI-EUR
- SUSHI-GBP
- SUSHI-USD
- SWELL-USD
- SWFTC-USD
- SXT-USD
- SYLO-USD
- SYLO-USDT
- SYN-USD
- SYND-USD
- SYRUP-USD
- T-USD
- TAO-USD
- THQ-USD
- TIA-USD
- TIME-USD
- TIME-USDT
- TNSR-USD
- TON-USD
- TONE-USD
- TOSHI-USD
- TOWNS-USD
- TRAC-EUR
- TRAC-USD
- TRAC-USDT
- TRB-BTC
- TRB-USD
- TREE-USD
- TRIBE-USD
- TROLL-USD
- TRU-BTC
- TRU-EUR
- TRU-USD
- TRU-USDT
- TRUMP-USD
- TRUST-USD
- TURBO-USD
- TVK-USD
- UMA-BTC
- UMA-EUR
- UMA-GBP
- UMA-USD
- UNFI-USD
- UNI-BTC
- UNI-EUR
- UNI-GBP
- UNI-USD
- UPI-USD
- UPI-USDT
- USD1-USD
- USDC-EUR
- USDC-GBP
- USDS-USD
- USDT-EUR
- USDT-GBP
- USDT-USD
- USDT-USDC
- USELESS-USD
- UST-EUR
- UST-USD
- UST-USDT
- VARA-USD
- VELO-USD
- VET-USD
- VGX-EUR
- VGX-USD
- VGX-USDT
- VOXEL-USD
- VTHO-USD
- VVV-USD
- W-USD
- WAMPL-USD
- WAMPL-USDT
- WAXL-USD
- WBTC-BTC
- WBTC-USD
- WCFG-BTC
- WCFG-EUR
- WCFG-USD
- WCFG-USDT
- WCT-USD
- WELL-USD
- WET-USD
- WIF-USD
- WLD-USD
- WLFI-USD
- WLUNA-EUR
- WLUNA-GBP
- WLUNA-USD
- WLUNA-USDT
- WMTX-USD
- XAN-USD
- XCN-USD
- XCN-USDT
- XLM-BTC
- XLM-EUR
- XLM-USD
- XLM-USDT
- XPL-USD
- XRP-BTC
- XRP-EUR
- XRP-GBP
- XRP-USD
- XRP-USDT
- XSGD-USDC
- XTZ-BTC
- XTZ-EUR
- XTZ-GBP
- XTZ-USD
- XYO-BTC
- XYO-EUR
- XYO-USD
- XYO-USDT
- YB-USD
- YFI-BTC
- YFI-USD
- YFII-USD
- ZEC-BTC
- ZEC-USD
- ZEC-USDC
- ZEN-BTC
- ZEN-USD
- ZEN-USDT
- ZETA-USD
- ZETACHAIN-USD
- ZK-USD
- ZKC-USD
- ZKP-USD
- ZORA-USD
- ZRO-USD
- ZRX-BTC
- ZRX-EUR
- ZRX-USD
metadata:
  source: coinbase
  count: 776
  last_updated: '2026-01-23T23:51:28.227723Z'
