product_ids:
- BTC-USD
- 00-USD
- 1INCH-BTC
- 1INCH-EUR
- 1INCH-GBP
- 1INCH-USD
- 2Z-USD
- A8-USD
- AAVE-BTC
- AAVE-EUR
- AAVE-GBP
- AAVE-USD
- ABT-USD
- ACH-USD
- ACH-USDT
- ACS-USD
- ACX-USD
- ADA-BTC

metadata:
  source: coinbase
  count: 765
  last_updated: '2025-12-16T00:09:38.787090Z'
